apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fitness-app
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: fitness.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fitness-app
                port:
                  number: 80

