apiVersion: v1
kind: Service
metadata:
  name: fitness-app
  labels:
    app: fitness-app
spec:
  type: ClusterIP
  selector:
    app: fitness-app
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP

